"""ISO 3166-1 country NAMES -> alpha-2, for STRUCTURED vendor fields only.

GENERATED. Do not hand-edit `NAME_TO_ALPHA2`; regenerate it with:

    uv venv /tmp/isogen && uv pip install --python /tmp/isogen/bin/python pycountry
    /tmp/isogen/bin/python -c "import pycountry; ..."   # see git history for the script

pycountry wraps Debian's pkg-isocodes, which is the maintained ISO register with
translations and deprecation history. It is a GENERATION-time tool only -- this package
keeps three runtime dependencies and does not add a fourth to read a static table.

WHY THIS IS NOT `vocab._COUNTRY_CODES`. That map is 62 names and is deliberately narrow
because it feeds PROSE matching -- `_COUNTRY_NAME_RE`, `split_place`, and the non-US
exclusion token list that `scoring._location_excluded` runs against free text. Merging
these 425 names into it would match `Georgia` (a US state), `Jordan`, `Chad` and `Turkey`
against ordinary location strings, and `vocab` carries a test pinning that no country name
in that map is also a US state name. THIS table is only ever applied to a vendor's own
structured country field, where the string is known to be a country and nothing else.

COVERAGE, measured against the 232 distinct country tokens one source actually sent in a
31,790-row harvest: 222 resolve here. Six of the remainder were fragments of names
containing a comma, produced by an adapter bug that joined a country ARRAY into a string;
they disappear once the array is passed through intact. The last three are below.
"""

# Hand-added, and each is a real gap rather than a convenience:
#   turkey    -- ISO renamed the country Turkiye in 2022. Vendors still send the old name,
#                and pycountry's lookup does not resolve it.
#   palestine -- the register carries "Palestine, State of"; the bare common form is what
#                arrives.
#   kosovo    -- has NO ISO 3166-1 code. XK is the de-facto placeholder used by the EU and
#                most payment systems. Recorded so the value is legible rather than dropped;
#                a consumer that needs strict ISO can reject it on sight.
_ALIASES = {"turkey": "TR", "palestine": "PS", "kosovo": "XK"}


def alpha2(name) -> str | None:
    """A country NAME from a vendor's structured field -> alpha-2, or None.

    Case-folded and alias-resolved. Returns None rather than guessing: an unmapped name is
    a data-quality signal the caller should keep verbatim, not a value to invent.
    """
    if not name:
        return None
    key = " ".join(str(name).strip().lower().split())
    return NAME_TO_ALPHA2.get(key) or _ALIASES.get(key)


NAME_TO_ALPHA2 = {
    'afghanistan': 'AF',
    'albania': 'AL',
    'algeria': 'DZ',
    'american samoa': 'AS',
    'andorra': 'AD',
    'angola': 'AO',
    'anguilla': 'AI',
    'antarctica': 'AQ',
    'antigua and barbuda': 'AG',
    'arab republic of egypt': 'EG',
    'argentina': 'AR',
    'argentine republic': 'AR',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bhutan': 'BT',
    'bolivarian republic of venezuela': 'VE',
    'bolivia': 'BO',
    'bolivia, plurinational state of': 'BO',
    'bonaire, sint eustatius and saba': 'BQ',
    'bosnia and herzegovina': 'BA',
    'botswana': 'BW',
    'bouvet island': 'BV',
    'brazil': 'BR',
    'british indian ocean territory': 'IO',
    'british virgin islands': 'VG',
    'brunei darussalam': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'cabo verde': 'CV',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cayman islands': 'KY',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'christmas island': 'CX',
    'cocos (keeling) islands': 'CC',
    'colombia': 'CO',
    'commonwealth of dominica': 'DM',
    'commonwealth of the bahamas': 'BS',
    'commonwealth of the northern mariana islands': 'MP',
    'comoros': 'KM',
    'congo': 'CG',
    'congo, the democratic republic of the': 'CD',
    'cook islands': 'CK',
    'costa rica': 'CR',
    'croatia': 'HR',
    'cuba': 'CU',
    'curaçao': 'CW',
    'cyprus': 'CY',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    "côte d'ivoire": 'CI',
    "democratic people's republic of korea": 'KP',
    'democratic republic of sao tome and principe': 'ST',
    'democratic republic of timor-leste': 'TL',
    'democratic socialist republic of sri lanka': 'LK',
    'denmark': 'DK',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'eastern republic of uruguay': 'UY',
    'ecuador': 'EC',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'falkland islands (malvinas)': 'FK',
    'faroe islands': 'FO',
    'federal democratic republic of ethiopia': 'ET',
    'federal democratic republic of nepal': 'NP',
    'federal republic of germany': 'DE',
    'federal republic of nigeria': 'NG',
    'federal republic of somalia': 'SO',
    'federated states of micronesia': 'FM',
    'federative republic of brazil': 'BR',
    'fiji': 'FJ',
    'finland': 'FI',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'french republic': 'FR',
    'french southern territories': 'TF',
    'gabon': 'GA',
    'gabonese republic': 'GA',
    'gambia': 'GM',
    'georgia': 'GE',
    'germany': 'DE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'grand duchy of luxembourg': 'LU',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guernsey': 'GG',
    'guinea': 'GN',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'haiti': 'HT',
    'hashemite kingdom of jordan': 'JO',
    'heard island and mcdonald islands': 'HM',
    'hellenic republic': 'GR',
    'holy see (vatican city state)': 'VA',
    'honduras': 'HN',
    'hong kong': 'HK',
    'hong kong special administrative region of china': 'HK',
    'hungary': 'HU',
    'iceland': 'IS',
    'independent state of papua new guinea': 'PG',
    'independent state of samoa': 'WS',
    'india': 'IN',
    'indonesia': 'ID',
    'iran': 'IR',
    'iran, islamic republic of': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'islamic republic of afghanistan': 'AF',
    'islamic republic of iran': 'IR',
    'islamic republic of mauritania': 'MR',
    'islamic republic of pakistan': 'PK',
    'isle of man': 'IM',
    'israel': 'IL',
    'italian republic': 'IT',
    'italy': 'IT',
    'jamaica': 'JM',
    'japan': 'JP',
    'jersey': 'JE',
    'jordan': 'JO',
    'kazakhstan': 'KZ',
    'kenya': 'KE',
    'kingdom of bahrain': 'BH',
    'kingdom of belgium': 'BE',
    'kingdom of bhutan': 'BT',
    'kingdom of cambodia': 'KH',
    'kingdom of denmark': 'DK',
    'kingdom of eswatini': 'SZ',
    'kingdom of lesotho': 'LS',
    'kingdom of morocco': 'MA',
    'kingdom of norway': 'NO',
    'kingdom of saudi arabia': 'SA',
    'kingdom of spain': 'ES',
    'kingdom of sweden': 'SE',
    'kingdom of thailand': 'TH',
    'kingdom of the netherlands': 'NL',
    'kingdom of tonga': 'TO',
    'kiribati': 'KI',
    "korea, democratic people's republic of": 'KP',
    'korea, republic of': 'KR',
    'kuwait': 'KW',
    'kyrgyz republic': 'KG',
    'kyrgyzstan': 'KG',
    "lao people's democratic republic": 'LA',
    'laos': 'LA',
    'latvia': 'LV',
    'lebanese republic': 'LB',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'macao': 'MO',
    'macao special administrative region of china': 'MO',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    'mexico': 'MX',
    'micronesia, federated states of': 'FM',
    'moldova': 'MD',
    'moldova, republic of': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'morocco': 'MA',
    'mozambique': 'MZ',
    'myanmar': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nepal': 'NP',
    'netherlands': 'NL',
    'new caledonia': 'NC',
    'new zealand': 'NZ',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'niue': 'NU',
    'norfolk island': 'NF',
    'north korea': 'KP',
    'north macedonia': 'MK',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'oman': 'OM',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestine, state of': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    "people's democratic republic of algeria": 'DZ',
    "people's republic of bangladesh": 'BD',
    "people's republic of china": 'CN',
    'peru': 'PE',
    'philippines': 'PH',
    'pitcairn': 'PN',
    'plurinational state of bolivia': 'BO',
    'poland': 'PL',
    'portugal': 'PT',
    'portuguese republic': 'PT',
    'principality of andorra': 'AD',
    'principality of liechtenstein': 'LI',
    'principality of monaco': 'MC',
    'puerto rico': 'PR',
    'qatar': 'QA',
    'republic of albania': 'AL',
    'republic of angola': 'AO',
    'republic of armenia': 'AM',
    'republic of austria': 'AT',
    'republic of azerbaijan': 'AZ',
    'republic of belarus': 'BY',
    'republic of benin': 'BJ',
    'republic of bosnia and herzegovina': 'BA',
    'republic of botswana': 'BW',
    'republic of bulgaria': 'BG',
    'republic of burundi': 'BI',
    'republic of cabo verde': 'CV',
    'republic of cameroon': 'CM',
    'republic of chad': 'TD',
    'republic of chile': 'CL',
    'republic of colombia': 'CO',
    'republic of costa rica': 'CR',
    'republic of croatia': 'HR',
    'republic of cuba': 'CU',
    'republic of cyprus': 'CY',
    "republic of côte d'ivoire": 'CI',
    'republic of djibouti': 'DJ',
    'republic of ecuador': 'EC',
    'republic of el salvador': 'SV',
    'republic of equatorial guinea': 'GQ',
    'republic of estonia': 'EE',
    'republic of fiji': 'FJ',
    'republic of finland': 'FI',
    'republic of ghana': 'GH',
    'republic of guatemala': 'GT',
    'republic of guinea': 'GN',
    'republic of guinea-bissau': 'GW',
    'republic of guyana': 'GY',
    'republic of haiti': 'HT',
    'republic of honduras': 'HN',
    'republic of iceland': 'IS',
    'republic of india': 'IN',
    'republic of indonesia': 'ID',
    'republic of iraq': 'IQ',
    'republic of kazakhstan': 'KZ',
    'republic of kenya': 'KE',
    'republic of kiribati': 'KI',
    'republic of latvia': 'LV',
    'republic of liberia': 'LR',
    'republic of lithuania': 'LT',
    'republic of madagascar': 'MG',
    'republic of malawi': 'MW',
    'republic of maldives': 'MV',
    'republic of mali': 'ML',
    'republic of malta': 'MT',
    'republic of mauritius': 'MU',
    'republic of moldova': 'MD',
    'republic of mozambique': 'MZ',
    'republic of myanmar': 'MM',
    'republic of namibia': 'NA',
    'republic of nauru': 'NR',
    'republic of nicaragua': 'NI',
    'republic of north macedonia': 'MK',
    'republic of palau': 'PW',
    'republic of panama': 'PA',
    'republic of paraguay': 'PY',
    'republic of peru': 'PE',
    'republic of poland': 'PL',
    'republic of san marino': 'SM',
    'republic of senegal': 'SN',
    'republic of serbia': 'RS',
    'republic of seychelles': 'SC',
    'republic of sierra leone': 'SL',
    'republic of singapore': 'SG',
    'republic of slovenia': 'SI',
    'republic of south africa': 'ZA',
    'republic of south sudan': 'SS',
    'republic of suriname': 'SR',
    'republic of tajikistan': 'TJ',
    'republic of the congo': 'CG',
    'republic of the gambia': 'GM',
    'republic of the marshall islands': 'MH',
    'republic of the niger': 'NE',
    'republic of the philippines': 'PH',
    'republic of the sudan': 'SD',
    'republic of trinidad and tobago': 'TT',
    'republic of tunisia': 'TN',
    'republic of türkiye': 'TR',
    'republic of uganda': 'UG',
    'republic of uzbekistan': 'UZ',
    'republic of vanuatu': 'VU',
    'republic of yemen': 'YE',
    'republic of zambia': 'ZM',
    'republic of zimbabwe': 'ZW',
    'romania': 'RO',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'rwandese republic': 'RW',
    'réunion': 'RE',
    'saint barthélemy': 'BL',
    'saint helena, ascension and tristan da cunha': 'SH',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint martin (french part)': 'MF',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'samoa': 'WS',
    'san marino': 'SM',
    'sao tome and principe': 'ST',
    'saudi arabia': 'SA',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'sint maarten (dutch part)': 'SX',
    'slovak republic': 'SK',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'socialist republic of viet nam': 'VN',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'south africa': 'ZA',
    'south georgia and the south sandwich islands': 'GS',
    'south korea': 'KR',
    'south sudan': 'SS',
    'spain': 'ES',
    'sri lanka': 'LK',
    'state of israel': 'IL',
    'state of kuwait': 'KW',
    'state of qatar': 'QA',
    'sudan': 'SD',
    'sultanate of oman': 'OM',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'sweden': 'SE',
    'swiss confederation': 'CH',
    'switzerland': 'CH',
    'syria': 'SY',
    'syrian arab republic': 'SY',
    'taiwan': 'TW',
    'taiwan, province of china': 'TW',
    'tajikistan': 'TJ',
    'tanzania': 'TZ',
    'tanzania, united republic of': 'TZ',
    'thailand': 'TH',
    'the state of eritrea': 'ER',
    'the state of palestine': 'PS',
    'timor-leste': 'TL',
    'togo': 'TG',
    'togolese republic': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'trinidad and tobago': 'TT',
    'tunisia': 'TN',
    'turkmenistan': 'TM',
    'turks and caicos islands': 'TC',
    'tuvalu': 'TV',
    'türkiye': 'TR',
    'uganda': 'UG',
    'ukraine': 'UA',
    'union of the comoros': 'KM',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united kingdom of great britain and northern ireland': 'GB',
    'united mexican states': 'MX',
    'united republic of tanzania': 'TZ',
    'united states': 'US',
    'united states minor outlying islands': 'UM',
    'united states of america': 'US',
    'uruguay': 'UY',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'venezuela': 'VE',
    'venezuela, bolivarian republic of': 'VE',
    'viet nam': 'VN',
    'vietnam': 'VN',
    'virgin islands of the united states': 'VI',
    'virgin islands, british': 'VG',
    'virgin islands, u.s.': 'VI',
    'wallis and futuna': 'WF',
    'western sahara': 'EH',
    'yemen': 'YE',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'åland islands': 'AX',
}
